[workspace]
members = ["crate/*"]
resolver = "2"

[workspace.package]
repository = "https://github.com/EKGF/ekg-rs"
readme = "./README.md"
keywords = ["digital-twin", "ekg", "knowledge-graph", "rdf", "aws"]
description = "Various utility Rust crates for Enterprise Knowledge Graph (EKG) architecture"
version = "0.0.7"
rust-version = "1.75"
edition = "2021"
authors = [
    "Jacobus Geluk <jacobus.geluk@ekgf.org>",
]
publish = true
license-file = "./LICENSE"

[profile.dev.package.backtrace]
opt-level = 3

[profile.dev]
# less code to include in binary
panic = 'abort'
# link time optimization using whole-program analysis
lto = false
# optimization over all code (better optimization, slower build)
codegen-units = 256
# optimization for size (more aggressive)
opt-level = 0
incremental = true
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
# less code to include in binary
panic = 'abort'
# link time optimization using whole-program analysis
lto = true
# optimization over all code (better optimization, slower build)
codegen-units = 1
# optimization for size (more aggressive)
opt-level = 'z'

[workspace.dependencies]
#
# Local crates
#
ekg-error = { path = "crate/ekg-error", version = "0.0.7" }
ekg-identifier = { path = "crate/ekg-identifier", version = "0.0.7" }
ekg-namespace = { path = "crate/ekg-namespace", version = "0.0.7" }
ekg-sparql = { path = "crate/ekg-sparql", version = "0.0.7" }
ekg-util = { path = "crate/ekg-util", version = "0.0.7" }
#
# Tracing & Logging
#
tracing = { version = "0.1", default-features = false, features = ["log"] }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["std", "fmt", "env-filter", "ansi"] }
test-log = { version = "0.2.14", default-features = false, features = ["trace"] }
#
# Error handling
#
thiserror = { version = "1.0.51", default-features = false, features = ["backtrace"] }
unreachable = "1.0.0"
simple-error = "0.3.0"
#
# Serialization
#
serde = { version = "1", features = ["std", "derive"], default-features = false }
serde_json = { version = "1", default-features = false, features = ["std"] }
serde_path_to_error = { version = "0.1.11", default-features = false }
serde_urlencoded = { version = "0.7", default-features = true }
indoc = { version = "2", default-features = true }
#
# IRI stuff
#
iri-string = { version = "0.7.0", default-features = false, features = ["serde", "alloc"] }
iref = { version = "3.1.3", default-features = false, features = ["serde"] }
#
# RDF stuff
#
spargebra = { version = "0.2.8", default-features = true, features = ["rdf-star"] }
rdftk_core = "0.3.1"
rdftk_iri = "0.1.9"
rdftk_io = { version = "0.2.1", default-features = false, features = ["turtle"] }
r2d2 = "0.8.1"
#
# Config stuff
#
ignore = { version = "0.4.21", default-features = false }
config = { version = "0.13.4", default-features = false, features = ["toml"] }
#
# Runtime stuff
#
tokio = { version = "1", default-features = false, features = ["macros", "full"] }
#
# AWS
#
lambda_runtime = { version = "0.9.0", default-features = true }
aws-config = { version = "1.1.1", default-features = true, features = ["behavior-version-latest"] }
aws-types = { version = "1.1.1", default-features = false }
aws-smithy-runtime = { version = "1.1.1", default-features = false, features = ["client", "tls-rustls", "connector-hyper-0-14-x"] }
aws-smithy-runtime-api = { version = "1.1.1", default-features = true }
aws-sdk-sfn = { version = "1.9.0", default-features = true, features = ["behavior-version-latest"] }
aws-sdk-neptune = { version = "1.10.0", default-features = true, features = ["behavior-version-latest"] }
aws-sdk-neptunedata = { version = "1.9.0", default-features = true, features = ["behavior-version-latest"] }
#
# HTTP Stuff
#
# Keep the versions of hyper and hyper-rustls in sync with the versions in aws-smithy-runtime
#
rustls = { version = "=0.22.2", default-features = false, features = ["logging", "ring", "tls12"] }
hyper = { version = "0.14.28", default-features = false, features = ["tcp", "backports", "deprecated", "full"] }
hyper-rustls = { version = "=0.25", default-features = false, features = ["http2", "tls12", "webpki-roots", "webpki-tokio", "logging"] }
hyper-util = { version = "0.1.2", default-features = false, features = ["client", "client-legacy", "http2"] }
salvo = { version = "0.65.1", default-features = false }
webpki-roots = "0.26.0"
mime = "0.3.17"
url = "2.5.0"
fluent-uri = "0.1.4"
reqwest = { version = "0.11.18", default-features = false, features = ["gzip", "json", "rustls-tls", "trust-dns", "stream"] }
reqwest-streams = { version = "0.2.5", default-features = false, features = ["json"] }
#
# Git Stuff
#
gix = { version = "0.58.0", default-features = true }
gix-discover = { version = "0.29.0", default-features = true }
#
# Other Stuff
#
lazy_static = "1.4.0"
const_format = "0.2.30"
chrono = { version = "0.4.23", features = ["serde"] }
num_enum = "0.7.0"
phf = { version = "0.11", features = ["macros"] }
fancy-regex = { version = "0.13.0", default-features = true }
rand = "0.8.5"
uuid = { version = "1.3.3", features = ["v4", "v5", "serde", "fast-rng"], default-features = false }
