tag_prefix = ""
from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "cargo set-version --workspace {{version}}",
]
post_bump_hooks = [
    "git push --no-verify",
    "git push origin {{version}} --no-verify",
    "cd crate/ekg-error && cargo publish",
    "cd crate/ekg-util && cargo publish",
    "cd crate/ekg-identifier && cargo publish",
    "cd crate/ekg-metadata && cargo publish",
    "cd crate/ekg-sparql && cargo publish",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "ekg-rs"
owner = "EKGF"
authors = [
    { username = "jgeluk", signature = "Jacobus Geluk" },
]

[bump_profiles]

[packages]
